name: minisd
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - pytorch-lightning==1.4.2
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
